testing canu/2.1.1

diff --git a/scripts/mtDNApipe b/scripts/mtDNApipe
--- a/scripts/mtDNApipe
+++ b/scripts/mtDNApipe
@@ -158,11 +158,12 @@ fi
 dw_date=`date "+%Y%m%d-%H%M%S"`;
 
 
-if ! [[ -e ${W_URL}/log/long_reads_file_list_$dw_date.txt ]] && [[ -z ${READ1} ]]; then
-
+if ! [[ -z ${READ1} ]]; then
+	
+printf "Missing long read file. Supply list of long reads as -1 <PB_list.txt>"
     #record Pacbio raw data files available in the cloud at the time of the analysis
-    printf "Collecting data using: aws s3 ls s3://genomeark/species/${SPECIES}/${ID}/genomic_data/pacbio/\n\n"
-    aws s3 --no-sign-request ls s3://genomeark/species/${SPECIES}/${ID}/genomic_data/pacbio/ | grep -oP "m.*.subreads.bam" | uniq > ${W_URL}/log/long_reads_file_list_$dw_date.txt
+#    printf "Collecting data using: aws s3 ls s3://genomeark/species/${SPECIES}/${ID}/genomic_data/pacbio/\n\n"
+#    aws s3 --no-sign-request ls s3://genomeark/species/${SPECIES}/${ID}/genomic_data/pacbio/ | grep -oP "m.*.subreads.bam" | uniq > ${W_URL}/log/long_reads_file_list_$dw_date.txt
 
 else
 
